<a href="https://colab.research.google.com/github/merdogan97/DAwPY/blob/main/DAwPy_S3_(Pandas_Series)_22_01_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

# **Pandas Lesson, Session - 3**

# **Pandas Series**

In [1]:
import pandas as pd
import numpy as np

# **Creating a Pandas Series**

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

# **Using Lists**

In [6]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series({'a': 10, 'b': 20, 'c': 30})

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

# **Using NumPy Arrays**

In [10]:
arr

array([10, 20, 30])

In [11]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(data=arr, index= labels)    # indexlerini değiştirebiliyoruz

a    10
b    20
c    30
dtype: int64

# **Using Dictionary**

In [13]:
pd.Series({'a': 10, 'b': 20, 'c': 30})

a    10
b    20
c    30
dtype: int64

In [14]:
d

{'a': 10, 'b': 20, 'c': 30}

In [15]:
pd.Series(d, index=["q", "c", "y"])   # tutan index varsa onu getitirir , eşleşenleri getiri diğerlerini none yapar

q     NaN
c    30.0
y     NaN
dtype: float64

In [17]:
# none ==> float
type(np.nan)

float

# https://www.educba.com/python-object-to-string/

# **Using Scalar Value**

In [18]:
pd.Series(data="Ahmet")

0    Ahmet
dtype: object

In [19]:
pd.Series(data="Ahmet", index=range(1,5))

1    Ahmet
2    Ahmet
3    Ahmet
4    Ahmet
dtype: object

# **Data in a Series**

A pandas Series can hold a variety of object types:

{} or set()

In [21]:
pd.Series([set, list, dict])# bir seri içinde muhafaza edebiliriz

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [23]:
pd.Series([set, list, dict])[0]([2,5,7,5,8,2])    # içinden çekebiliriz 0:indexleme

{2, 5, 7, 8}

In [24]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [25]:
pd.Series([sum, print, len])[0]([3,5,7])    # sum old.için toplar

15

In [26]:
mix_data = ['Aziz', 2, True]

In [28]:
ser= pd.Series(mix_data)
ser           # karışık olursa object verir

0    Aziz
1       2
2    True
dtype: object

In [29]:
ser.dtype

dtype('O')

In [30]:
type(ser)

pandas.core.series.Series

In [31]:
type(ser[0])

str

In [32]:
type(ser[1])

int

In [33]:
type(ser[2])

bool

In [34]:
arr= np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [35]:
type(arr[0])# array tipini değiştirdi ; sseries muhafaza etti

numpy.str_

In [36]:
type(arr[1])  # array tipini değiştirdi ; sseries muhafaza etti

numpy.str_

In [37]:
type(arr[2])# array tipini değiştirdi ; sseries muhafaza etti

numpy.str_

In [43]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'guido': 4127, 'jack': 4098, 'sape': 4139}

# **Basic Attributes of Series**

In [39]:
ser= pd.Series(np.random.randint(0,100,7))
ser

0     9
1    89
2    56
3     0
4    71
5    83
6    74
dtype: int64

In [40]:
type(ser)   # seri olduğunu görebiliyoruz

pandas.core.series.Series

In [41]:
ser.dtype

dtype('int64')

In [42]:
ser.shape     # satır sayısını verir tek boyutlu

(7,)

In [44]:
ser.size

7

In [45]:
ser.ndim

1

In [46]:
len(ser)

7

In [47]:
ser.index     # indexleri göstermez ,ama bçimini verir

RangeIndex(start=0, stop=7, step=1)

In [48]:
list(ser) # listeyi gösterir

[9, 89, 56, 0, 71, 83, 74]

In [49]:
for i in ser.index:
  print(i)

0
1
2
3
4
5
6


In [51]:
ser.keys()    # index ile aynı işlemi yapar

RangeIndex(start=0, stop=7, step=1)

In [52]:
ser.values    # değerleri array olarak döndürür

array([ 9, 89, 56,  0, 71, 83, 74])

In [56]:
ser.items

<bound method Series.items of 0     9
1    89
2    56
3     0
4    71
5    83
6    74
dtype: int64>

In [57]:
ser.items()

In [58]:
list(ser.items())

[(0, 9), (1, 89), (2, 56), (3, 0), (4, 71), (5, 83), (6, 74)]

In [60]:
for index, value in ser.items():      # diğer bir yöntem
  print(f"index: {index}, value: {value}")

index: 0, value: 9
index: 1, value: 89
index: 2, value: 56
index: 3, value: 0
index: 4, value: 71
index: 5, value: 83
index: 6, value: 74


In [62]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c    13
b    23
a    20
e    15
f    11
d     1
g     4
i    23
h    17
j     9
dtype: int64

In [63]:
ser.head()    # default 5 tir

c    13
b    23
a    20
e    15
f    11
dtype: int64

In [64]:
ser.tail()

d     1
g     4
i    23
h    17
j     9
dtype: int64

In [65]:
ser.sample(3)   # datadan herhangi bir 3 satır getirir

c    13
b    23
d     1
dtype: int64

In [66]:
ser.sort_index()

a    20
b    23
c    13
d     1
e    15
f    11
g     4
h    17
i    23
j     9
dtype: int64

In [67]:
ser.sort_index(ascending=True)    # alfabetik sıraladı

a    20
b    23
c    13
d     1
e    15
f    11
g     4
h    17
i    23
j     9
dtype: int64

In [68]:
ser.sort_values(ascending= False) # default True

i    23
b    23
a    20
h    17
e    15
c    13
f    11
j     9
g     4
d     1
dtype: int64

In [69]:
ser

c    13
b    23
a    20
e    15
f    11
d     1
g     4
i    23
h    17
j     9
dtype: int64

In [70]:
ser.isin([5,9]) # hangi değerlerim 5,9 

c    False
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j     True
dtype: bool

In [72]:
ser.isin([11,15])

c    False
b    False
a    False
e     True
f     True
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [73]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

# **Indexing Pandas Series**

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [74]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [75]:
ser1.sort_index() # alf. sıra

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [76]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [77]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [78]:
ser1.sort_index() # alf. sıra

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [79]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [80]:
ser1[1]   

2

In [81]:
ser1["Germany"]

2

In [82]:
ser1.Germany      # "string" ise böyle de olur  az kullanılır  ser1.2 olmaz

2

# **Operations are then also done based off of index:**

In [83]:
ser1 + ser2 # aynı indexleri topluyor yoksa none çeviriyorr .  **** Seri içinde nonelar old.için float oldu

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [84]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [85]:
ser3[0]

'a'

In [86]:
ser3[:2]

0    a
1    b
dtype: object

In [89]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

# **pandas_series[index] | pandas_series[[indices, indices...]]**

In [90]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [91]:
panser[["terry", "orion"]]

terry    121
orion    150
dtype: int64

In [92]:
panser["terry": "orion"]# : koyup [] ları kaldırabiliriz

terry      121
micheal    200
orion      150
dtype: int64

In [93]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

# **Recap for Several Selecting Attributes an d Some Attributes**

In [94]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [96]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [97]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [98]:
panser.values

array([121, 200, 150,  99])

In [102]:
panser.items()

In [103]:
for index, value in panser.items():   # iterable bir data döndürüür
  print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [104]:
"terry" in panser

True

In [105]:
"bob"in panser

False

In [106]:
200 in panser.values      # value değeri sorgulayacaksak

True

In [107]:
panser.index        # aynısını yapar

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [108]:
panser.isin([200, 150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [109]:
panser["terry"]= 90
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [110]:
panser[panser>100]

micheal    200
orion      150
dtype: int64

In [112]:
panser[panser>100]=175    # 100'den büyüklere 175 atadım
panser

terry       90
micheal    175
orion      175
jason       99
dtype: int64