<a href="https://colab.research.google.com/github/merdogan97/DAwPY/blob/main/Numpy%26Pandas_Assignment_1_25_01_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [2]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [3]:
my_list=[5,10,15,20,25]
my_array = np.array(my_list)
my_array

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [4]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [5]:
np.ones((4, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [6]:
np.ones((4, 4), dtype=int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [7]:
np.full((4,4), "7", dtype=int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [8]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,25, dtype=int).reshape(5,5) # default 50

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [11]:
np.random.rand(5)   # 0-1 arasında

array([0.53146493, 0.7032363 , 0.97693146, 0.2235441 , 0.67440792])

#### 11. Create random normal distributed 5x5 array

In [10]:
np.random.randn(5,5) 

array([[ 1.42616788, -0.70812217,  0.80932705, -0.2094325 ,  0.6802897 ],
       [ 0.07588578, -0.62583866, -0.65616128,  0.13500072,  0.01792623],
       [ 1.03764512,  0.0677884 , -0.6179081 , -1.77832501,  1.34330179],
       [ 0.27802313,  1.51000299,  0.58357416,  0.95040037,  0.47017976],
       [ 1.26893779, -0.73540383, -0.53948583, -0.5949858 , -0.6955116 ]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [15]:
np.random.randint(20, 50, (3,4))

array([[47, 24, 24, 48],
       [31, 43, 40, 28],
       [33, 33, 34, 40]])

#### 13. Reshape the array below with shape 6x8

In [16]:
ranarr = np.array

In [17]:
ranarr = np.random.randint(1,100, (6,8))

In [18]:
ranarr

array([[59, 26, 67,  5, 78,  2, 68,  2],
       [84, 32, 34, 61, 57, 56, 52, 23],
       [15, 87, 37, 52, 96, 93, 15, 56],
       [75, 61, 31,  7, 93, 81, 82, 11],
       [50, 36, 90, 50, 72, 31, 92, 73],
       [77, 63, 22, 80, 19, 92, 87, 37]])

In [66]:
ranarr.reshape(-1, 8)

array([[59, 26, 67,  5, 78,  2, 68,  2],
       [84, 32, 34, 61, 57, 56, 52, 23],
       [15, 87, 37, 52, 96, 93, 15, 56],
       [75, 61, 31,  7, 93, 81, 82, 11],
       [50, 36, 90, 50, 72, 31, 92, 73],
       [77, 63, 22, 80, 19, 92, 87, 37]])

## Numpy Indexing and Selection


In [20]:
#Create array below
mat=np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [21]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [22]:
mat[:4, 0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [23]:
np.arange(5,8,2)

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [24]:
mat[:4, 2]=77   
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [25]:
mat[[1,3], [0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [27]:
mat[1::2,::2]    #mat[1::2, [0,2]]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [81]:
mat[mat<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
mat[mat>12]

array([13, 14, 15, 16])

In [31]:
mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
(mat[mat<10] + mat[mat>12]).std()

In [ ]:
a = [78, 79, 81, 18, 20, 85, 25]
np.std(a)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
mat[0:4, 1].sum()  # sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [32]:
mat=np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
mat[2, 0:4]

array([ 9, 10, 11, 12])

In [34]:
mat[2]

array([ 9, 10, 11, 12])

In [35]:
np.median(mat[2])


10.5

In [36]:
np.mean(mat[2])


10.5

In [37]:
np.std(mat[2])


1.118033988749895

## **Pandas Section**

In [38]:
import pandas as pd

# **Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [85]:
sal=pd.read_csv('Salaries.csv')

In [86]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [87]:
sal.info

<bound method DataFrame.info of             Id       EmployeeName  ...         Agency  Status
0            1     NATHANIEL FORD  ...  San Francisco     NaN
1            2       GARY JIMENEZ  ...  San Francisco     NaN
2            3     ALBERT PARDINI  ...  San Francisco     NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5    PATRICK GARDNER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN
148653  148654          Joe Lopez  ...  San Francisco     NaN

[148654 rows x 13 columns]>

In [ ]:
sal.describe().T

count          mean  ...         75%        max
Id                148654.0  74327.500000  ...  111490.750  148654.00
BasePay           148045.0  66325.448841  ...   94691.050  319275.01
OvertimePay       148650.0   5066.059886  ...    4658.175  245131.88
OtherPay          148650.0   3648.767297  ...    4236.065  400184.25
Benefits          112491.0  25007.893151  ...   35566.855   96570.66
TotalPay          148654.0  74768.321972  ...  105839.135  567595.43
TotalPayBenefits  148654.0  93692.554811  ...  132876.450  567595.43
Year              148654.0   2012.522643  ...    2014.000    2014.00
Notes                  0.0           NaN  ...         NaN        NaN
Status                 0.0           NaN  ...         NaN        NaN

[10 rows x 8 columns]

**How many different year value are there**

In [89]:
sal.Year

0         2011
1         2011
2         2011
3         2011
4         2011
          ... 
148649    2014
148650    2014
148651    2014
148652    2014
148653    2014
Name: Year, Length: 148654, dtype: int64

In [88]:
sal.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [ ]:
sal.TotalPay.max()

567595.43

In [45]:
sal.TotalPay.min()

63534.97

In [ ]:
sal.TotalPay.mean()

74768.321971703

# **How many records are there which have TotalPay bigger than avg TotalPay**

In [91]:
len(sal.[sal.TotalPay > sal.TotalPay.mean()])

SyntaxError: ignored

In [59]:
sal.TotalPay[sal.TotalPay>sal.TotalPay.mean()].count()

8431

**How much does ALBERT PARDINI make (including benefits)?**

In [51]:
sal.TotalPayBenefits[sal["EmployeeName"]=="ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [92]:
sal[sal.TotalPayBenefits == sal.TotalPayBenefits.min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [93]:
sal.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [56]:
sal["JobTitle"].value_counts().sort_values()[0:3]
# sal.JobTitle.value_counts().sort_values()[:3]

MOBILE EQUIPMENT SUPERVISOR       1
SENIOR MAINTENANCE CONTROLLER     1
JANITORIAL SERVICES SUPERVISOR    1
Name: JobTitle, dtype: int64

In [96]:
sal.JobTitle.value_counts().tail(3)

Light Rail Vehicle Equip Eng         1
ASSISTANT INDUSTRIAL HYGIENIST       1
LIEUTENANT I, (POLICE DEPARTMENT)    1
Name: JobTitle, dtype: int64

# **How many people earned more than avg in 2012**

In [102]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.mean()) & (sal.Year==2012)]["EmployeeName"].count()

20366

# **How many people have the word Manager in their job title?**

In [103]:
def manager_func(x):
  if 'manager' in x.lower():
      return True
  else:
      return False

In [104]:
len(sal[sal.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [65]:
sal_new = sal.iloc[:, [0,1,2,7,8]]
sal_new.head()

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0   1     NATHANIEL FORD  ...  567595.43         567595.43
1   2       GARY JIMENEZ  ...  538909.28         538909.28
2   3     ALBERT PARDINI  ...  335279.91         335279.91
3   4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4   5    PATRICK GARDNER  ...  326373.19         326373.19

[5 rows x 5 columns]

In [73]:
sal_new

Id         EmployeeName  ...   TotalPay  TotalPayBenefits
0          1       NATHANIEL FORD  ...  567595.43         567595.43
1          2         GARY JIMENEZ  ...  538909.28         538909.28
2          3       ALBERT PARDINI  ...  335279.91         335279.91
3          4    CHRISTOPHER CHONG  ...  332343.61         332343.61
4          5      PATRICK GARDNER  ...  326373.19         326373.19
...      ...                  ...  ...        ...               ...
19918  19919    STEPHANI THOMPSON  ...   63538.40          63538.40
19919  19920      CYNTHIA VASQUEZ  ...   63538.40          63538.40
19920  19921       SANDA WIN THAW  ...   63536.37          63536.37
19921  19922  CHARLES BRIDGEWATER  ...   63534.97          63534.97
19922  19923      DIMITRI SHIKALO  ...        NaN               NaN

[19923 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [74]:
sal_new= sal_new.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new

EmployeeName  ... TotalPayBenefits
0           NATHANIEL FORD  ...        567595.43
1             GARY JIMENEZ  ...        538909.28
2           ALBERT PARDINI  ...        335279.91
3        CHRISTOPHER CHONG  ...        332343.61
4          PATRICK GARDNER  ...        326373.19
...                    ...  ...              ...
19918    STEPHANI THOMPSON  ...         63538.40
19919      CYNTHIA VASQUEZ  ...         63538.40
19920       SANDA WIN THAW  ...         63536.37
19921  CHARLES BRIDGEWATER  ...         63534.97
19922      DIMITRI SHIKALO  ...              NaN

[19923 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [75]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.min()) & (sal.TotalPayBenefits < sal.TotalPayBenefits.mean())]["EmployeeName"]

8431          MICHAEL ROSS
8432            LAURA MOYE
8433         LARRY MERRITT
8434           JAMES PERRY
8435             TONY WONG
               ...        
19916        DIANA OQUENDO
19917      GAIL VAN SCIVER
19918    STEPHANI THOMPSON
19919      CYNTHIA VASQUEZ
19920       SANDA WIN THAW
Name: EmployeeName, Length: 11490, dtype: object