<a href="https://colab.research.google.com/github/merdogan97/DAwPY/blob/main/NumPy_setup_and_Operations_19_01_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.19.5'

In [ ]:
Creating NumPy arrays from a list,  
Creating NumPy arrays using built-in methods such as:
    .arange       ,     Returns an ndarray object containing evenly spaced values within a given range.
    .linspace     ,      Returns the number of evenly spaced values between the interval is specified
    .random       ,     Return random floats in the half-open interval [0.0, 1.0).
    .zeros        ,      Returns a new array of specified size, filled with zero 
    .ones        ,       Returns a new array of specified size and type, filled with ones
    .eye         ,        Return a 2-D array with ones on the diagonal and zeros elsewhere

In [ ]:
Array attributes and methods such as:
    .shape      ,  the shape tuple give the lengths of the corresponding array dimensions.
    .reshape    , Gives a new shape to an array without changing its data.
    .max        ,  Return the maximum along a given axis.
    .min        , Return the minimum along a given axis.
    .argmax     ,  Return the index of the maximum element along a given axis
    .argmin     . Return the index of the minimum element along a given axis

In [ ]:
np.arange

<function numpy.arange>

In [ ]:
a= [1,2,3]    # pyhton list
[q*2 for q in a]

[2, 4, 6]

In [ ]:
a = np.array([1,2,3])     # numpy  
a*2

array([2, 4, 6])

In [ ]:
a = [1,2,3]
b = [4,5,6]
[ q+r for q, r in zip(a,b)]     # pyhton list

[5, 7, 9]

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

Other than that, **NumPy arrays** are:

1.   faster than lists when the operation can be vectorized

2.   slower than lists when you append elements to the end

3.  more compact, especially when there’s more than one dimension
4.  usually homogeneous: can only work fast with elements of one type









In [ ]:
a = np.array([5,6,9])
a[0]

5

In [ ]:
a[1]

6

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim  

2

In [ ]:
a = np.array([5,6,9])
a.ndim

1

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim  

2

In [ ]:
a.itemsize

8

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array([[1,2],[3,4],[5,6]], dtype= np.float64)
a.ndim  

2

In [ ]:
a


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
a.size

6

In [ ]:
a
a.shape

(3, 2)

In [ ]:
a = np.array([[1,2],[3,4],[5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
l = range(5)
l

range(0, 5)

In [ ]:
l[0]

0

In [ ]:
l[3]

3

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(2,3,8)

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        ])

In [ ]:
np.linspace(30,100,5)

array([ 30. ,  47.5,  65. ,  82.5, 100. ])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [ ]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a.ravel()       # tek dimemsion haline getirir

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.min()

1

In [ ]:
a.max()

6

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)   # sütünları toplar

array([ 9, 12])

In [ ]:
a.sum(axis=1)   # satırları toplar 

array([ 3,  7, 11])

In [ ]:
a.sqrt()

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.std(a)

1.707825127659933

In [ ]:
a= np.array([[1,2], [3,4]])
b= np.array([[5,6], [7,8]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a*2

array([[2, 4],
       [6, 8]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [63]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d



array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [64]:
 arr_2d[0,2]

15

In [ ]:
In NumPy Operations lesson you will learn:

Following arithmetic operations with NumPy:
   - addition, return the sum of arr1 and arr2 
   - subtraction, return the difference of arr1 and arr2
   - division, return an array element from first array is divided by elements from second element
   - multiplication, returns the product of arr1 and arr2

In [ ]:
Universal array functions such as:
   - square root, returns the square root of the number in an array.
   - exponential, return an array with exponential of all elements of input array

   - max,  return the maximum along a given axis.
   - min, return the minimum along a given axis.
   - mean, returns mean along specific axis
   - median, computes the median along the specified axis

   - std,  returns the standard deviation of specific axis
   - sum, returns sum of arr
   - mod ( remainder), returns element-wise remainder of division.
   - sin,  The sine of each element of x. This is a scalar if x is a scalar (2pi radian equals 360 degrees)

In [65]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [66]:
arr_2d[2,1]

40

In [67]:
arr_2d[:1,1:]

array([[10, 15]])

In [68]:
arr=np.arange(1,37)
arr.shape

(36,)