<a href="https://colab.research.google.com/github/merdogan97/DAwPY/blob/main/NumPy_Recap(23_01_2022).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
np.__version__

'1.19.5'

In [10]:
np.__name__

'numpy'

In [11]:
np.__NUMPY_SETUP__

False

In [12]:
np._globals

<module 'numpy._globals' from '/usr/local/lib/python3.7/dist-packages/numpy/_globals.py'>

In [13]:
np.__version__

'1.19.5'

In [14]:
np.arange

<function numpy.arange>

In [15]:
a = [1,2,3,4]

In [17]:
[b*2 for b in a]

[2, 4, 6, 8]

In [24]:
c = np.array(a)

In [25]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [26]:
c*2

array([2, 4, 6, 8])

In [27]:
c**3

array([ 1,  8, 27, 64])

In [28]:
c/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [30]:
b = [5,6,7,8]

In [32]:
d = np.array(b)
d

array([5, 6, 7, 8])

In [33]:
c+d

array([ 6,  8, 10, 12])

In [34]:
a = np.array([2,5,8,9,])

In [35]:
a[2]

8

In [36]:
a[0]


9

In [37]:
a[1]

5

In [38]:
a[3]

9

In [39]:
a[2]

8

In [40]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim  

2

In [42]:
a                #    axis0 and axis1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
a[0]

array([1, 2])

In [44]:
a[1]

array([3, 4])

In [45]:
a[2]

array([5, 6])

In [46]:
a.itemsize

8

In [51]:
t = np.array([[1,2],[3,4],[5,6],[7,8],[11,12]])

In [52]:
t.itemsize

8

In [56]:
s = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
s.ndim

2

In [60]:
p = np.array([[[1,2,3,4]], [[5,6,7,8]],[[9,10,11,12]]])
p

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [61]:
p.ndim

3

In [62]:
p.itemsize

8

In [65]:
p.dtype

dtype('int64')

In [66]:
print(type(p))

<class 'numpy.ndarray'>


In [67]:
p.size

12

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
t.size

10

In [79]:
t.itemsize

8

In [80]:
t.ndim

2

In [82]:
l = range(5)
l

range(0, 5)

In [84]:
print([l])

[range(0, 5)]


In [86]:
l[2]

2

In [87]:
np.arange(3,5)

array([3, 4])

In [89]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [92]:
np.arange(0, 5, 0.5, dtype=float)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [93]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [94]:
np.arange(-3, 3, 0.5, dtype=float)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [96]:
np.arange(0,100,10, dtype=float)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [97]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [98]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [99]:
np.linspace(0,20,4, dtype=int)

array([ 0,  6, 13, 20])

In [100]:
np.linspace(2,4,10, dtype=float)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [102]:
np.linspace(2,4,10, dtype=int)

array([2, 2, 2, 2, 2, 3, 3, 3, 3, 4])

In [103]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [104]:
np.linspace(1,5,20, dtype=int)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5])

In [105]:
t.shape

(5, 2)

In [106]:
p.shape

(3, 1, 4)

In [108]:
s.shape

(3, 4)

In [109]:
p.shape

(3, 1, 4)

In [110]:
t.shape   # 5 satır, 2 sütun

(5, 2)

In [111]:
t.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8, 11, 12]])

In [112]:
s.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [113]:
a = np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [114]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [118]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
t.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12])

In [121]:
s.ravel 

<function ndarray.ravel>

In [122]:
s.ravel( )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
p.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [124]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [127]:
s.min

<function ndarray.min>

In [129]:
s.max()

12

In [128]:
s.min()

1

In [130]:
s.sum()

78

In [131]:
p.sum()

78

In [137]:
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [139]:
b = [1,3,5,7]
b= np.array(b)
b

array([1, 3, 5, 7])

In [143]:
a.sum()

20

In [142]:
b.sum()

16

In [144]:
b.sum(axis=0)

16

In [148]:
c= np.array([[1,2,3,4],[5,6,6,7]])
c

array([[1, 2, 3, 4],
       [5, 6, 6, 7]])

In [150]:
c.sum(axis=0)

array([ 6,  8,  9, 11])

In [151]:
c.sum(axis=1)

array([10, 24])

In [152]:
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.44948974, 2.64575131]])

In [154]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [155]:
arr_2d[0,2]

15

In [156]:
arr_2d[2,0]

35

In [157]:
arr_2d[:1,1:]

array([[10, 15]])